# Generated by Django 4.2.1 on 2023-05-13 10:54

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftFunc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equation", models.CharField(max_length=50)),
                ("range_of_func", models.CharField(max_length=50)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[("dashed", "DASHED"), ("dotted", "DOTTED")],
                        max_length=50,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="")),
                ("file_link", models.CharField(max_length=100)),
                (
                    "graph_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_fontsize", models.IntegerField()),
                (
                    "title_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
                ("x_label", models.CharField(max_length=50)),
                ("y_label", models.CharField(max_length=50)),
                ("z_label", models.CharField(max_length=50)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
