# Generated by Django 4.2.1 on 2023-05-24 19:23

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftFunc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default="title", max_length=50)),
                ("title_fontsize", models.IntegerField(default=13)),
                (
                    "title_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "equation",
                    models.CharField(
                        max_length=50,
                        verbose_name="Equation in terms of x,y and z (function should be given in python math syntax, ex: x**2+y**2)",
                    ),
                ),
                (
                    "range_of_func",
                    models.CharField(
                        default="[(-10, 10), (-10, 10), (-10, 10)]",
                        max_length=50,
                        verbose_name="supply in the format of 3 tuples inside one list: [(x_min,x_max), (y_min,y_max), (z_min,z_max)]",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[("dashed", "DASHED"), ("dotted", "DOTTED")],
                        max_length=50,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="datasets/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "xslsx"]
                            )
                        ],
                    ),
                ),
                (
                    "file_link",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="File link(if the file is not uploaded)",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_fontsize", models.IntegerField(default=13)),
                (
                    "title_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
                (
                    "graph_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=18, samples=None
                    ),
                ),
                ("x_label", models.CharField(default="x", max_length=50)),
                ("y_label", models.CharField(default="y", max_length=50)),
                (
                    "z_label",
                    models.CharField(blank=True, default="z", max_length=50, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
