# Generated by Django 4.2.1 on 2023-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftdataset",
            name="file",
            field=models.FileField(default=None, upload_to=""),
        ),
        migrations.AlterField(
            model_name="draftdataset",
            name="file_link",
            field=models.CharField(
                default=None,
                max_length=100,
                verbose_name="File link(if the file is not uploaded)",
            ),
        ),
    ]
