# Generated by Django 4.2.1 on 2023-05-13 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0002_alter_draftdataset_file_alter_draftdataset_file_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftdataset",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xslsx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="draftdataset",
            name="file_link",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="File link(if the file is not uploaded)",
            ),
        ),
    ]
