# Generated by Django 4.2.1 on 2023-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0003_alter_draftdataset_file_alter_draftdataset_file_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftdataset",
            name="title_fontsize",
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name="draftdataset",
            name="x_label",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="draftdataset",
            name="y_label",
            field=models.CharField(default="y", max_length=50),
        ),
        migrations.AlterField(
            model_name="draftdataset",
            name="z_label",
            field=models.CharField(default="z", max_length=50),
        ),
    ]
