# Generated by Django 4.2.1 on 2023-05-20 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0004_alter_draftdataset_title_fontsize_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftdataset",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="datasets/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xslsx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="draftdataset",
            name="z_label",
            field=models.CharField(blank=True, default="z", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="draftfunc",
            name="equation",
            field=models.CharField(
                max_length=50, verbose_name="Equation in terms of x,y and z"
            ),
        ),
    ]
