# Generated by Django 4.2.1 on 2023-05-20 19:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0005_alter_draftdataset_file_alter_draftdataset_z_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftfunc",
            name="title",
            field=models.CharField(default="title", max_length=50),
        ),
        migrations.AddField(
            model_name="draftfunc",
            name="title_color",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AddField(
            model_name="draftfunc",
            name="title_fontsize",
            field=models.IntegerField(default=13),
        ),
    ]
