# Generated by Django 4.2.1 on 2023-05-23 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0006_draftfunc_title_draftfunc_title_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftfunc",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
