# Generated by Django 4.2.1 on 2023-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0007_draftfunc_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftfunc",
            name="equation",
            field=models.CharField(
                max_length=50,
                verbose_name="Equation in terms of x,y and z (function should be given in python math syntax, ex: x**2+y**2)",
            ),
        ),
        migrations.AlterField(
            model_name="draftfunc",
            name="range_of_func",
            field=models.CharField(
                default="[(-10, 10, 100), (-10, 10, 100)]",
                max_length=50,
                verbose_name="supply in the format of 2 tuples inside one list: [(start of x, stop of x, number of x ),(start of y, stop of y, number of y)]",
            ),
        ),
    ]
