# Generated by Django 4.2.1 on 2023-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0008_alter_draftfunc_equation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftfunc",
            name="range_of_func",
            field=models.CharField(
                default="[(-10, 10), (-10, 10), (-10, 10)]",
                max_length=50,
                verbose_name="supply in the format of 3 tuples inside one list: [(x_min,x_max), (y_min,y_max), (z_min,z_max)]",
            ),
        ),
    ]
