# Generated by Django 4.2.1 on 2023-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0009_alter_draftfunc_range_of_func"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftdataset",
            name="file_link",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="File link(if the file is not uploaded)",
            ),
        ),
    ]
